name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.9+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  # google_speech: ^5.3.0
  mic_stream: ^0.7.2
  # permission_handler: ^11.0.0+1
  # record: ^6.0.0

  speech_to_text: ^7.0.0
  google_speech: ^5.3.0        # Core package for Google Cloud Speech-to-Text via gRPC [3]
  permission_handler: ^11.3.1  # For requesting microphone permissions [15]
  # sound_stream: ^0.4.0        # For capturing microphone audio stream [16] (Inferred dependency) - Replaced by mic_stream
  path_provider: ^2.1.3       # Often used by google_speech examples/internals [1, 2, 4, 17]
  googleapis_auth: ^1.6.0
  grpc: ^3.2.4
  # Optional but recommended for secure credential handling:
  # flutter_dotenv: ^5.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
